= Create your first Enonic application
:toc: right
:experimental:
:imagesdir: media/
:sourcedir: ../

Create, build and deploy an application based on a starter

== Intro

The expression "There's an app for that" fits well with Enonic. When you created the sandbox, several applications were automatically installed (based on the `Essentials` template), which extended the platform's capabilities.

https://developer.enonic.com/docs/platform/stable/apps[Enonic apps^] are containers for content schemas, as well as code and platform extensions, which we will dive into later.


== Create an app

*Open a new terminal window* and create your first Enonic app by running this command:

  enonic create com.example.myapp -r tutorial-intro -s mysandbox

This command will:

* use the GitHub repo `github.com/enonic/tutorial-intro` as a starter
* to create an app called `com.example.myapp`
* in the directory `myapp` setting version number to `1.0.0`
* and link it to `mysandbox` which you created earlier

TIP: A pre-compiled standard version of this app is also available on https://market.enonic.com/vendors/enonic/introduction[Enonic Market^].

=== Project structure

Inside the `myapp` directory, you should now have a file structure looking something like this:

.Selected files from the app code:
[source,files]
----
docs/ <1>
samples/ <2>
src/
 main/
  resources/
   assets/ <3>
   cms/ 
    content-types/ <4>
    ...   
   i18n/ <5>
   import/ <6>
   lib/ <7>
   enonic.yaml <8>
----

<1> The documentation you are reading now
<2> Code samples that will be used in this guide
<3> Static assets for sample preview
<4> https://developer.enonic.com/docs/cms/xp8/content/content-types[Content Type schemas]
<5> Sample content
<6> https://developer.enonic.com/docs/code/stable/fundamentals/i18n[Localisation bundles]
<7> https://developer.enonic.com/docs/code/stable/fundamentals/functions[Sample preview code]
<8> App details

== Build and deploy

Assuming `mysandbox` is still running in another Terminal window, run these commands:

  cd myapp
  enonic dev

The last command (`dev`) will build the app, deploy it to `mysandbox`, and start continuously watching for changes in the source code, automatically deploying the changes without you having to rebuild/redeploy the app after each change.

[NOTE]
====
The initial build may take a while.  Look for these lines to confirm it has completed:

```
Waiting for changes to input files...
│···············│ 0% EXECUTING [31s]
> :dev
```
====

== Moving forward

You just created and built your very own application. In the next chapter you'll get familiar with <<cms#, Content Studio and content modelling>>.
